<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbf8dd9e4350a3fb2c9e8e259a829d642
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbf8dd9e4350a3fb2c9e8e259a829d642::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbf8dd9e4350a3fb2c9e8e259a829d642::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbf8dd9e4350a3fb2c9e8e259a829d642::$classMap;

        }, null, ClassLoader::class);
    }
}
